services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres

    postgres:
      image: postgres:17-alpine
      container_name: psgr
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${DATABASE_NAME}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      networks:
        - dbnet

  networks:
    dbnet:
      driver: bridge

  volumes:
    postgres-data:






